language: node_js
node_js: node
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  api_key:
    secure: ZY1jTfNfl/TV6o1ALv/eeEP7rgRsnGQuY2QTPrw38/CDEeGv2aj/lZ7p2ITM6xh0Y3xdgnyY/w3q4ddHnq0zEiAQRD3bKLz6tQMi+0b8nuFilyCimHnCOCmBLnmQlhqNJciWszmFvaLXqz/nrJoY+JLZyCd9QNJ4LpbbRxELqBFqkc5Hdo6NlcTvg33+iM8baMx8H7R9wV6YisRSuFgV2fBfItUWfzaVwBORilVJh41+YZnW8F7w9hzT2xHI3/FOWt1FzomPcyWPTzB8XDO8RSPHZrV/4o7epGIfKN4PG4NYvt4WB3DuY0iVqcEGQ6hjZc0jC6UBmtpgXjQcRFo15qKrDjKk/p+APOuRs7MyXTwE9qXXhww/xtZI0SBkUIjzULiXUEDPslhOZ7I0Tl7zaNmzTOhNzIhmx3XbfvAVoFWVTg5nGTm/1+/GNUX4tDGeS6lY+CvO4qcXBUKk7EL2IoFnlZAcOs3a/0QzaoPJkPcbzaDt+GIiRgRD0RzyNhh4++h/at5Ejhq0JYbQibjkb1sIF21aSHyWUGrJ9kqJx21VfpXSqc4JBov3LUqQa0rl3IGcyYo51qitkWy0e9q9CM+bq9pw6SXtldAoqa2mo/TMQJODOCMkCHmfOMMhSE95IytAcSwkotxE8MikHGixCIo+Oc05+pu1PIFoFmqr2wE=
  app: frozen-brook-34776
  on:
    repo: jmkeller3/wait2plate-server
