language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: 5U/yV2wKhuKxf7JsZkQlE1//T7CplCybQYyk7EMFINvxPc0JUBktD00NCC6ojOscaUYsYorAcY+P+0cIHPLfTL/6hXizgrHB9+dtGU/+r/S7Qq98Y6ZiDWqAEs2DvoOLiG4cmJ0uzaFqChKMm1ixMPrsLiRGdEiNKK87Gl/bL0JmqIFAmNz2jUpyinEeAJZSlrD3DQLoBIT9hiQGlE06UMbZahJbJV3IVRpLHLi8M0O/dcNH1tNQw5lHRRZvhKXiOeibyw0HZBHatYKjVN/rQDiyQTjO5Q1b9Y/CB+YKor76kiGhSKxIxGo56JhKmoWkkIMeaz8lqL2Cj32KrK1pP3nFJG1PWBPeNtGjcbI+igx9Gp0PHbKaBgb4pNCn6XGWmNsIKEK15hCd510dKzuaOicC8mf9DyS8dsHgs06eVVG/8vrzuS4EzVSEsbTh7xRDgwE7K12eMCAKjZyx0N0KYeXua9lqSxCE9J9KWnn7smjxnEJLhCHmoFaSwQEOTa3wLAPME8VQiONWQP6Ut0cZF2ornybYgVVzGDC7RW0sh5+xH8F4tOPhcJxewwrmQn2GuZob+ZeaWcTlUcnebkN+C/qkxfsATZUImDp9/4/mHmIpFhzg5oKsaoOLmQLN1M8dj9eIHgQrJM3xtQ7FTr9NjBIcKaaWihKwVp/GQUcAmG8=
  app: frozen-brook-34776
  on:
    repo: jmkeller3/wait2plate-server
