language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: DaYdUwqv6rWQthjPLORZw2J6NPhOjWrr4AP8QLYpSrXDXUTZaM147HTjheXfamnCe+tW8c5E++NRlj0LjfCQTX1iJfRihNd3kv6e/BjTkn2Zfd713OgpSX21u516EWIO1lTEcljwamQQQs7b5M3wS2gfrUAuN8D8BBsb68ZFahREYp6sBFylaBrwclwIhpMjWbYFq5liHpxvKcRCzrhKVX+oFYFOaQ5nahyRV0bejGCkoLYZb9s32PqkkQTAqumtnCTEYvTplHuJVYW1mtg/bqoJbSTvqB1RJ/4njtKZKjlUkRQsd7EpghfP54yxxHtE1MuRlTdMmyZN7ASjjtnW/mZCjQoSTio0hp54rExxlWgMvpwJSle/8U9UeZ++1HVNsRyKqyAdiQ+m4aiWOBWjxUbsfiPlszPtAON16ab2WWaj7yeYQpz6Ojt30J2xpFeP2mFtS/uWEkjMWEvXVGd6QX4wvl42C3qe7o8+HlrEqwrP5PAQsCGPPhHVUvpobweWdxUuBHzHAkNo+o82WKONDCd7N8WQpw0XPGc5Fd8ZSyWIeV0fiVBaxcTqt/wDSbKLUhxq4+p8+3S7HapDJOaa9ViIIVGSpc8ZHpjbe8bYX7ohu7AN8AcxiMcXiN7P/ddCzcv3Ez0zSfuZH08hMUrv6vlbZ0rngdn3OlwOiLDkyKo=
  app: frozen-brook-34776
  on:
    repo: jmkeller3/wait2plate-server
